
### Test SPA
GET http://localhost:3000

### Ver usuarios (primera vista por defecto)
GET http://localhost:3000/

### Listar todos los usuarios (API)
GET http://localhost:3000/api/users

### Crear usuario (API)
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Santiago",
    "email": "santiago@test.com"
}

### Obtener usuario por ID (API)
GET http://localhost:3000/api/users/6984f7f5f26d1f8a62f92f3e

### Actualizar usuario (API)
PUT http://localhost:3000/api/users/6984f7f5f26d1f8a62f92f3e
Content-Type: application/json

{
    "name": "Santiago Actualizado",
    "email": "santiago.nuevo@test.com"
}

### Eliminar usuario (API)
DELETE http://localhost:3000/api/users/6984f7f5f26d1f8a62f92f3e
